#! /bin/bash
unset BOSPHORUS_VERSION

function bosphorus() {
	local dir="$PWD/" machine_name return_value

	until [[ -z "$dir" ]]; do
		dir="${dir%/*}"

		if { read -r machine_name <"$dir/.docker-machine"; } 2>/dev/null || [[ -n "$machine_name" ]]; then
			machine_name="${machine_name%%[[:space:]]}"

			if [[ "$machine_name" == "$BOSPHORUS_VERSION" ]]; then return
			else
        echo "Setting active docker-machine to" $machine_name
        eval $(docker-machine env $machine_name)
        return_value=$?
        BOSPHORUS_VERSION="$machine_name"
        if [[ $return_value -ne 0 ]] ; then
          echo "Failed to switch to" $machine_name
        fi
				return $return_value
			fi
		fi
	done
}

if [[ -n "$ZSH_VERSION" ]]; then
	if [[ ! "$precmd_functions" == *bosphorus* ]]; then
		precmd_functions+=("bosphorus")
	fi
elif [[ -n "$BASH_VERSION" ]]; then
	if [[ "$PROMPT_COMMAND" == "" ]]; then
    PROMPT_COMMAND="bosphorus"
  else
    PROMPT_COMMAND=$PROMPT_COMMAND && "bosphorus"
  fi
fi
